/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package expresat;

/**
 *
 * @author Migue
 */
public class Calificar_Persona extends javax.swing.JFrame {

    /**
     * Creates new form Calificar_Persona
     */
    public Calificar_Persona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("1 Estrella");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(478, 10, 130, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2 Estrellas");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(478, 50, 130, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("3 Estrellas");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(478, 90, 130, 23);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("4 Estrellas");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(478, 130, 130, 23);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("5 Estrellas");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(478, 170, 130, 23);

        jButton1.setText("Aceptar");
        jButton1.setMaximumSize(new java.awt.Dimension(75, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(478, 240, 80, 23);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(626, 240, 80, 23);

        jList1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 410, 568);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("10 Estrellas");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(626, 170, 110, 23);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("9 Estrellas");
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(626, 130, 110, 23);

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("8 Estrellas");
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(626, 90, 110, 23);

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("7 Estrellas");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(626, 50, 110, 23);

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("6 Estrellas");
        getContentPane().add(jRadioButton10);
        jRadioButton10.setBounds(626, 10, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
