/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package expresat;

/**
 *
 * @author Migue
 */
public class Contrato extends javax.swing.JFrame {

    /**
     * Creates new form Contrato
     */
    public Contrato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jButton1.setText("Terminar");
        getContentPane().add(jButton1);
        jButton1.setBounds(467, 461, 87, 23);

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2);
        jButton2.setBounds(586, 461, 86, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("No, acepto los terminos indicados en el contrato.");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(10, 436, 662, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Acepto los terminos indicados en el contrato.");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(10, 410, 662, 23);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 662, 392);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
