/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package expresat;

/**
 *
 * @author Migue
 */
public class Registrar_Entidad extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_Entidad
     */
    public Registrar_Entidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jButton1.setText("Registrar");
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 210, 90, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 40, 220, 20);

        jLabel1.setText("Nombre del ente o la institución:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 170, 14);

        jButton2.setText("Atrás");
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 240, 90, 23);

        jLabel2.setText("Cédula jurídica:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 100, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 70, 220, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección"));
        jPanel1.setLayout(null);

        jLabel3.setText("País*:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 30, 40, 14);

        jLabel4.setText("Provincia*:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 50, 70, 14);

        jLabel5.setText("Cantón*:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 70, 60, 14);

        jLabel6.setText("Distrito*:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 90, 60, 14);

        jLabel7.setText("Barrio:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 110, 32, 14);

        jLabel8.setText("* campos obligados");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 140, 170, 14);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(80, 30, 170, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(80, 50, 170, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(80, 70, 170, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(80, 90, 170, 20);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(80, 110, 170, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 160, 260, 160);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(180, 100, 220, 20);

        jLabel9.setText("Categoría:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 100, 110, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
